# -*- coding: utf-8 -*-
"""Habit Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sD7C5ZGLmMgFTzvPy_OvvdGMyl2o_bui
"""

import datetime
import random

# Motivational quotes
quotes = [
    "🌱 Every day is a new chance to build your dreams.",
    "🏆 Consistency is your secret weapon.",
    "💪 The best project you'll ever work on is YOU.",
    "🎯 Small habits lead to big results. Keep going!"
]

# Milestones
milestones = {
    3: "🎉 3 days streak! Great job!",
    7: "🚀 1 week! Keep going!",
    14: "🌟 Two weeks! Amazing!",
    30: "🏅 30 days! You’re unstoppable!"
}

def streak(dates):
    if not dates: return 0
    dates = sorted(dates)
    dt = [datetime.datetime.strptime(d, "%Y-%m-%d").date() for d in dates]
    streak = 0
    for i in range(len(dt)-1, 0, -1):
        if (dt[i] - dt[i-1]).days == 1:
            streak += 1
        else:
            break
    if dt and dt[-1] == datetime.date.today():
        return streak + 1
    return 0

# --- Main code ---
print("\n" + random.choice(quotes))
print("Welcome to the Habit Tracker!\n")

habits = ["Drink Water", "Read"]
logs = {habit: set() for habit in habits}

while True:
    print("\nYour habits:", ", ".join(habits))
    print("1. Add a new habit")
    print("2. Log habits for today")
    print("3. View habit history & streaks")
    print("4. Quit")
    choice = input("Choose an option (1-4): ").strip()

    if choice == "1":
        new_habit = input("Enter the new habit name: ").strip().title()
        if new_habit and new_habit not in habits:
            habits.append(new_habit)
            logs[new_habit] = set()
            print(f"Added: {new_habit}")
        else:
            print("Invalid or duplicate habit.")
    elif choice == "2":
        today = datetime.date.today().strftime("%Y-%m-%d")
        for habit in habits:
            if today in logs[habit]:
                print(f"{habit}: Already logged for today.")
            else:
                ans = input(f"Did you complete '{habit}' today? (y/n): ").strip().lower()
                if ans == "y":
                    logs[habit].add(today)
                    print(f"Logged: {habit}")

                    s = streak(logs[habit])
                    print(f"Current streak for '{habit}': {s} days")
                    if s in milestones:
                        print(milestones[s])
    elif choice == "3":
        for habit in habits:
            habit_dates = sorted(logs[habit])
            print(f"\nHabit: {habit}")
            print(f"Days logged: {len(habit_dates)}")
            print("Last 10 days:", habit_dates[-10:])
            s = streak(logs[habit])
            print(f"Current streak: {s}")
            if s in milestones:
                print(milestones[s])
    elif choice == "4":
        print("Goodbye! Keep building your habits! ❤️")
        break
    else:
        print("Invalid choice. Please select from the menu.")